version: '3.1'

services:
  postgres:
    hostname: 'postgres-db'
    image: postgres:16.1-alpine
    restart: always
    ports: [5432:5432]
    environment:
      TZ: 'Europe/Rome'
      PGTZ: 'Europe/Rome'
      POSTGRES_DB: 'ProTrc'
      POSTGRES_USER: 'utente1'
      POSTGRES_PASSWORD: 'password1'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 1s
      timeout: 2s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'

  svelte-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
